---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
       upgrade: dist
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates for Fedroa
    tags: always
    ansible.builtin.dnf:
       use_backend: dnf
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: create user
    tags: always
    ansible.builtin.user:
      name: AdrianK
      groups: root

  - name: add sudoers file for AdrianK
    tags: always
    ansible.builtin.copy:
      src: sudoer_AdrianK
      dest: /etc/sudoers.d/AdrianK
      owner: root
      group: root
      mode: 0440

  - name: add ssh key for AdrianK
    tags: always
    ansible.builtin.authorized_key:
      user: AdrianK
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZUplFGOAvuC7cWbd4nA/qeNPA40oPg/ZlCO0z+8Za9 adrian@ubuntu-ws"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache
    tags: apache,ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"


  - name: install apache for Fedora
    tags: apache,fedora
    ansible.builtin.dnf:
       name: httpd
       use_backend: dnf
    when: ansible_distribution == "Fedora"


  - name: ensure apache is running
    tags: apache,ubuntu
    ansible.builtin.service:
       name: apache2
       state: started
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache is running on Fedora
    tags: apache,fedora
    ansible.builtin.service:
       name: httpd
       state: started
    when: ansible_distribution == "Fedora"


  - name: change email address 
    tags: apache,fedora
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin adrian@adrian.com
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: restart httpd fedora
    tags: apache,fedora
    ansible.builtin.service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy html
    tags: apache,ubuntu
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  tags: db,fedora
  become: true
  tasks:
    - name: install mariadb package on db servers
      ansible.builtin.dnf:
        name: mariadb
        use_backend: dnf
        state: latest
      when: ansible_distribution == "Fedora"



